server {
    listen 443 ssl;

    root /usr/share/nginx/html;
    index index.html;
    server_name lordarchieve.com www.lordarchieve.com;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;


    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name lordarchieve.com www.lordarchieve.com;
	return 301 https://$host$request_uri;
}

